language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
yarn: true
before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to a file to be used later
  - echo "$SSH_PRIVATE_KEY" | base64 --decode > bit_rsa
  # Provide the proper permissions for the ssh keys
  - chmod 600 bit_rsa
  # Adding ssh key to agent
  - ssh-add bit_rsa
  # Adding bit-bin for being able to use bit commands later
  # @TODO: Alias dev dependency binary (i.e. ./node_modules/.bin/bit) instead of installing
  - npm install bit-bin -g
  # buidl
  - yarn build

script:
  - GIT_HASH=$(git rev-parse --short HEAD)
  - if [ "$TRAVIS_BRANCH" = "develop" -a ! "$TRAVIS_PULL_REQUEST" = "false" ]; then HOST=$(echo ui-develop.mybit.io); fi
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then HOST=$(echo ui-staging.mybit.io); fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then HOST=$(echo ui.mybit.io); fi
  - echo ${GIT_HASH} > build/version
  - cp CONTRIBUTORS build/contributors
  - BUILD_URL=$(npx now --name ui.mybit.io build -t $NOW_PROD_TOKEN)
  - npx now alias ${BUILD_URL} $HOST -t $NOW_PROD_TOKEN

after_success:
  - npm set init.author.name "MyBit AG"
  - npm set init.author.email "mybit.development@gmail.com"
  - npm config set @bit:registry = "https://node.bitsrc.io"
  - echo "//registry.npmjs.org/:_authToken=$NPM_MYBIT_BOT_TOKEN" > ~/.npmrc
  - echo "//node.bitsrc.io/:_authToken=$NPM_MYBIT_BOT_TOKEN" >> ~/.npmrc
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit config set analytics_reporting; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit config set error_reporting; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit config set user.name jjperezaguinaga; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit config set user.email me@jjperezaguinaga.com; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit config set ssh_key_file bit_rsa; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit init; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit add src/showcase/*; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit tag --all; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "true" ]; then bit export mybit.ui; fi
