language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
yarn: true
before_script:
  - yarn test
  - yarn build
script:
  - GIT_HASH=$(git rev-parse --short HEAD)
  - if [ "$TRAVIS_BRANCH" = "develop" -a ! "$TRAVIS_PULL_REQUEST" = "false" ]; then HOST=$(echo ui-develop.mybit.io); fi
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then HOST=$(echo ui-staging.mybit.io); fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then HOST=$(echo ui.mybit.io); fi
  - echo ${GIT_HASH} > build/version
  - cp CONTRIBUTORS build/contributors
  - BUILD_URL=$(npx now --name $HOST -e HOST=$HOST -t $NOW_PROD_TOKEN)
  - npx now alias ${BUILD_URL} $HOST -t $NOW_PROD_TOKEN
