version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      - run: yarn test

      - run: yarn build

      - deploy:
          name: Deploy to Now
          command: |
            GIT_HASH=$(git rev-parse --short HEAD)
            SANITIZED_BRANCH=$(tr "/" "-" <<<$CIRCLE_BRANCH)
            VERY_SANITIZED_BRANCH=$(tr "." "-" <<<$SANITIZED_BRANCH)
            HOST=$(echo $VERY_SANITIZED_BRANCH-ui-mybit-io-dev.now.sh)
            echo ${GIT_HASH} > version
            cp CONTRIBUTORS contributors
            npx now rm ui.mybit.io -t $NOW_DEVELOPMENT_TOKEN --yes || true
            echo ${HOST}
            BUILD_URL=$(npx now --name ui.mybit.io -e HOST=$HOST -t $NOW_DEVELOPMENT_TOKEN --public)
            npx now alias ${BUILD_URL} ${HOST} -t $NOW_DEVELOPMENT_TOKEN
